# Generated by Django 5.0.7 on 2024-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
