# Generated by Django 5.0.7 on 2024-10-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_remove_users_first_name_remove_users_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
