# Generated by Django 5.0.7 on 2024-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(default='images/supplier_logos/default.jpg', upload_to='supplier_logos/'),
        ),
    ]
