# Generated by Django 5.0.7 on 2024-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0002_supplier_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
