# Generated by Django 5.0.7 on 2024-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0003_alter_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person_job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplied_products',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Food', 'Food'), ('Books', 'Books'), ('Toys', 'Toys'), ('Tools', 'Tools'), ('Sports', 'Sports'), ('Beauty', 'Beauty'), ('Health', 'Health'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(default='supplier_logos/default.jpg', upload_to='supplier_logos/'),
        ),
    ]
