# Generated by Django 5.0.7 on 2024-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0005_supplier_services_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='services_offered',
            field=models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Installation', 'Installation'), ('Warranty', 'Warranty'), ('Support', 'Support'), ('Maintenance', 'Maintenance')], max_length=50, null=True),
        ),
    ]
