# Generated by Django 5.0.7 on 2024-07-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0006_alter_supplier_services_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='rating',
        ),
    ]
