# Generated by Django 5.0.7 on 2024-07-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0009_supplier_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='policy',
            field=models.CharField(blank=True, choices=[('No Returns', 'No Returns'), ('Exchange Only', 'Exchange Only'), ('Refund Only', 'Refund Only'), ('Exchange or Refund', 'Exchange or Refund'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='services_offered',
            field=models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Installation', 'Installation'), ('Warranty', 'Warranty'), ('Support', 'Support'), ('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Consultation', 'Consultation'), ('Customization', 'Customization'), ('Upgrades', 'Upgrades'), ('Training', 'Training'), ('Inspection', 'Inspection'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
